# CREATE USER
CREATE USER 'ADMINISTRADOR'@'%' IDENTIFIED By 'ADM_123';
CREATE USER 'MAGISTRADO'@'%' IDENTIFIED By 'MAG_123';
CREATE USER 'ANALISTA_JUDICIARIO'@'%' IDENTIFIED By 'ANA_123';
CREATE USER 'TECNICO_JUDICIARIO'@'%' IDENTIFIED By 'TEC_123';

# GRANT ADMINISTRADOR
GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON *.* TO 'ADMINISTRADOR'@'%';

# GRANT MAGISTRADO
GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON *.* TO 'MAGISTRADO'@'%';

# GRANT ANALISTA_JUDICIARIO
GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON *.* TO 'ANALISTA_JUDICIARIO'@'%';

# GRANT TECNICO_JUDICIARIO
GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON *.* TO 'TECNICO_JUDICIARIO'@'%';

# SELECT * FROM mysql.user;
