# CREATE USER
CREATE USER 'ADMINISTRADOR'@'%' IDENTIFIED By 'ADM_123';
CREATE USER 'MAGISTRADO'@'%' IDENTIFIED By 'MAG_123';
CREATE USER 'ANALISTA_JUDICIARIO'@'%' IDENTIFIED By 'ANA_123';
CREATE USER 'TECNICO_JUDICIARIO'@'%' IDENTIFIED By 'TEC_123';
CREATE USER 'CONCILIADOR'@'%' IDENTIFIED By 'CON_123';
CREATE USER 'REPRESENTANTE'@'%' IDENTIFIED By 'REP_123';

# GRANT ADMINISTRADOR
GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON *.* TO 'ADMINISTRADOR'@'%';

# GRANT MAGISTRADO
GRANT SELECT, EXECUTE ON *.* TO 'MAGISTRADO'@'%';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.Magistrado TO 'MAGISTRADO';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.Endereco TO 'MAGISTRADO';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.Documento TO 'MAGISTRADO';

# GRANT ANALISTA_JUDICIARIO
GRANT SELECT, EXECUTE ON *.* TO 'ANALISTA_JUDICIARIO'@'%';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.Servidor TO 'ANALISTA_JUDICIARIO';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.Endereco TO 'ANALISTA_JUDICIARIO';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.Documento TO 'ANALISTA_JUDICIARIO';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.Movimentacao TO 'ANALISTA_JUDICIARIO';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.Execucao TO 'ANALISTA_JUDICIARIO';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.Recebimento TO 'ANALISTA_JUDICIARIO';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.CursoEspecializacao TO 'ANALISTA_JUDICIARIO';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.Parte TO 'ANALISTA_JUDICIARIO';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.ParteFisica TO 'ANALISTA_JUDICIARIO';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.ParteJuridica TO 'ANALISTA_JUDICIARIO';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.Execucao TO 'ANALISTA_JUDICIARIO';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.Recebimento TO 'ANALISTA_JUDICIARIO';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.Representante TO 'ANALISTA_JUDICIARIO';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.Pauta TO 'ANALISTA_JUDICIARIO';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.Audiencia TO 'ANALISTA_JUDICIARIO';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.Testemunha TO 'ANALISTA_JUDICIARIO';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.ProcessoTestemunha TO 'ANALISTA_JUDICIARIO';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.Pauta TO 'ANALISTA_JUDICIARIO';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.Testemunha TO 'ANALISTA_JUDICIARIO';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.ProcessoTestemunha TO 'ANALISTA_JUDICIARIO';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.ComunicacaoParte TO 'ANALISTA_JUDICIARIO';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.ComunicacaoTestemunha TO 'ANALISTA_JUDICIARIO';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.CorrespondenciaParte TO 'ANALISTA_JUDICIARIO';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.CorrespondenciaTestemunha TO 'ANALISTA_JUDICIARIO';

# GRANT TECNICO_JUDICIARIO
GRANT SELECT, EXECUTE ON *.* TO 'TECNICO_JUDICIARIO'@'%';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.Servidor TO 'TECNICO_JUDICIARIO';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.Endereco TO 'TECNICO_JUDICIARIO';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.Documento TO 'TECNICO_JUDICIARIO';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.Movimentacao TO 'TECNICO_JUDICIARIO';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.Execucao TO 'TECNICO_JUDICIARIO';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.Recebimento TO 'TECNICO_JUDICIARIO';

# GRANT CONCILIADOR
GRANT SELECT, EXECUTE ON *.* TO 'CONCILIADOR'@'%';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.Servidor TO 'CONCILIADOR';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.Endereco TO 'CONCILIADOR';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.Documento TO 'CONCILIADOR';

# GRANT REPRESENTANTE
GRANT SELECT, EXECUTE ON *.* TO 'REPRESENTANTE'@'%';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.Representante TO 'REPRESENTANTE';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.Parte TO 'REPRESENTANTE';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.ParteFisica TO 'REPRESENTANTE';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.ParteJuridica TO 'REPRESENTANTE';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.Processo TO 'REPRESENTANTE';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.Testemunha TO 'REPRESENTANTE';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.ProcessoTestemunha TO 'REPRESENTANTE';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.ProcessoFeito TO 'REPRESENTANTE';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.ProcessoParte TO 'REPRESENTANTE';
GRANT INSERT, UPDATE, DELETE ON DBSPJC.Documento TO 'REPRESENTANTE';


# SELECT * FROM mysql.user;







